### ISSUE TITLE
初期設定をボタン一つでできる方法を用意する

### ISSUE THREAD

**Issue by ryutoiee** [toiee-lab/kanso-general#24]
![2018-02-09 16 51 12](https://user-images.githubusercontent.com/32448204/36017083-950357a0-0db9-11e8-9b6e-b2497bb5dca2.png)

**Comment by toiee-kameda** [comment]
> ラベルと、タイトルを変更

---

初期設定をボタン一つでできるようにすれば、とても簡単になる。おそらく「インポーター」の機能を実装すればいい。有料テーマなどでも使われているので、色々方法があるはず。調べれば、解決する問題だ。
